SELECT 
    AG.AGE_NAME AS "年齢階層",
    SUM(CASE WHEN STD.TIME_CODE = 120 THEN STD.TARGET_POP ELSE 0 END) AS "5時間未満",
    SUM(CASE WHEN STD.TIME_CODE = 130 THEN STD.TARGET_POP ELSE 0 END) AS "5時間以上6時間未満",
    SUM(CASE WHEN STD.TIME_CODE = 140 THEN STD.TARGET_POP ELSE 0 END) AS "6時間以上7時間未満",
    SUM(CASE WHEN STD.TIME_CODE = 150 THEN STD.TARGET_POP ELSE 0 END) AS "7時間以上8時間未満",
    SUM(CASE WHEN STD.TIME_CODE = 160 THEN STD.TARGET_POP ELSE 0 END) AS "8時間以上9時間未満",
    SUM(CASE WHEN STD.TIME_CODE = 170 THEN STD.TARGET_POP ELSE 0 END) AS "9時間以上",
    SUM(CASE WHEN STD.TIME_CODE = 180 THEN STD.TARGET_POP ELSE 0 END) AS "不詳"
FROM SLEEP_TIME_DTL AS STD
    INNER JOIN AGE_GRP AS AG ON (STD.AGE_CODE = AG.AGE_CODE)
    INNER JOIN SLEEP_TIME AS ST ON (STD.TIME_CODE = ST.TIME_CODE AND ST.TIME_CODE)
GROUP BY
    AG.AGE_CODE
ORDER BY
    AG.AGE_CODE