SELECT 
    POPU15.PF_CODE AS 都道府県コード,
    PRE.PF_NAME AS 都道府県名,
    POPU15.TOTAL_AMT AS 総人口2015年,
    POPU20.TOTAL_AMT AS 総人口2020年,
    ROUND(100*CAST(POPU20.TOTAL_AMT AS REAL)/CAST(POPU15.TOTAL_AMT AS REAL), 0) AS 人口増加率
FROM 
    POPU_TRANSITION AS POPU15
    INNER JOIN PREFECTURE AS PRE ON (POPU15.PF_CODE = PRE.PF_CODE)
    INNER JOIN POPU_TRANSITION AS POPU20 ON (POPU15.PF_CODE = POPU20.PF_CODE AND POPU20.SURVEY_YEAR = 2020)
WHERE
    POPU15.SURVEY_YEAR = 2015
    AND POPU15.TOTAL_AMT < POPU20.TOTAL_AMT
ORDER BY
    人口増加率 DESC,
    都道府県コード