SELECT
    PORT.PORT_CODE AS "港コード",
    PORT.PORT_NAME AS "港名",
    SUM(CASE WHEN IM.KIND_CODE=110 THEN IM.AMT ELSE 0 END) AS "入国者数",
    SUM(CASE WHEN IM.KIND_CODE=120 THEN IM.AMT ELSE 0 END) AS "出国者数",
    SUM(CASE WHEN IM.KIND_CODE=110 THEN IM.AMT ELSE 0 END) - SUM(CASE WHEN IM.KIND_CODE=120 THEN IM.AMT ELSE 0 END) AS "差分"
FROM IMMIGRATION AS IM
    INNER JOIN PORT ON (IM.PORT_CODE = PORT.PORT_CODE)
    INNER JOIN GRP ON (IM.GROUP_CODE = GRP.GROUP_CODE)
WHERE IM.GROUP_CODE = 120
GROUP BY PORT.PORT_CODE
HAVING "差分" > 0
ORDER BY "差分" DESC, PORT.PORT_CODE DESC;