SELECT
    PRE.PF_CODE AS CODE,
    PF_NAME AS NAME,
    ROUND(100*SUM(CASE DH.CATEGORY_CODE WHEN '120' THEN DH.AMT ELSE 0 END)/SUM(CASE DH.CATEGORY_CODE WHEN '110' THEN DH.AMT ELSE 0 END), 1) AS PERCENTAGE
FROM DRINK_HABITS AS DH
    INNER JOIN PREFECTURE AS PRE
    ON DH.PF_CODE = PRE.PF_CODE
WHERE DH.GENDER IN ('2', '3')
GROUP BY DH.PF_CODE
ORDER BY
    PERCENTAGE DESC,
    DH.PF_CODE DESC;